com:
    demo:
        uploads:
            directory: storage

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/file_db
        driverClassName: org.postgresql.Driver
        username: postgres
        password: fury
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    redis:
        host: localhost
        port: 6379
        password:

sfox:
file-share:
    cache:
        expire_time_mills: 100000000