apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-sharing-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: file-sharing-1
  template:
    metadata:
      labels:
        app: file-sharing-1
    spec:
      containers:
        - name: file-sharing-1
          image: file-sharing-1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
